# Generated by Django 2.1.1 on 2018-11-12 12:24

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mentors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('observation', models.TextField()),
                ('note_for_next_meeting', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MeetingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mentorees/meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Mentoree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('dream', models.CharField(blank=True, max_length=128, null=True)),
                ('want_to_become', models.CharField(blank=True, max_length=32, null=True)),
                ('fears', models.CharField(blank=True, max_length=128, null=True)),
                ('loves', models.CharField(blank=True, max_length=64, null=True)),
                ('hates', models.CharField(blank=True, max_length=64, null=True)),
                ('strengths', models.CharField(blank=True, max_length=64, null=True)),
                ('extra_data', models.CharField(blank=True, max_length=128, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='mentorees/profile')),
                ('extra_data_fields', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(default=dict), blank=True, null=True, size=None)),
                ('story', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MentorLicenceKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='\\d{3}[a-zA-z]{3}')])),
            ],
        ),
        migrations.CreateModel(
            name='MentorQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('middle_name', models.CharField(max_length=32)),
                ('nationality', models.CharField(max_length=265)),
                ('registration_address', models.CharField(max_length=521)),
                ('religion', models.CharField(choices=[('CHRISTIANITY', 'Християнство'), ('CATHOLICISM', 'Католицизм'), ('ORTHODOXY', 'Православ’я'), ('PROTESTANTISM', 'Протестантизм'), ('JUDAISM', 'Іудаїзм'), ('BUDDHISM', 'Буддизм'), ('ISLAM', 'Іслам'), ('OTHER', 'Інше')], max_length=20)),
                ('local_church_visiting', models.CharField(blank=True, max_length=256, null=True)),
                ('local_church_visiting_frequency', models.CharField(blank=True, choices=[('ONCE_A_WEEK', 'раз на тиждень'), ('ONCE_A_MONTH', 'раз на місяць'), ('ONCE_A_YEAR', 'один раз на рік'), ('OTHER', 'інше')], max_length=20, null=True)),
                ('health_self_estimation', models.CharField(max_length=265)),
                ('serious_diseases', models.BooleanField(default=False)),
                ('narcologist', models.BooleanField(default=False)),
                ('psychiatrist', models.BooleanField(default=False)),
                ('phthisiatrician', models.BooleanField(default=False)),
                ('therapist', models.BooleanField(default=False)),
                ('dermatovenereologist', models.BooleanField(default=False)),
                ('hospital_data', models.CharField(blank=True, max_length=512, null=True)),
                ('hiv_infected', models.BooleanField(default=False)),
                ('interests_and_hobbies', models.TextField()),
                ('marital_status', models.CharField(choices=[('MARRIED', 'Одружений/одружена'), ('CIVIL_MARRIAGE', 'Цивільний шлюб'), ('DIVORCED', 'Розлучений/розлучена'), ('WIDOW', 'Удовець/удова'), ('UNMARRIED', 'Неодружений/неодружена')], max_length=20)),
                ('home_type', models.CharField(choices=[('APARTMENT', 'квартира'), ('PRIVATE_HOUSE', 'приватний будинок'), ('RENTED', 'орендоване житло')], max_length=20)),
                ('room_count', models.PositiveSmallIntegerField(default=1)),
                ('people_per_room', models.PositiveSmallIntegerField(default=1)),
                ('home_family_members_data', models.TextField()),
                ('pets_data', models.TextField()),
                ('join_reason', models.TextField()),
                ('helpful_specifics', models.TextField()),
                ('self_char', models.TextField()),
                ('want_to_help_reason', models.TextField()),
                ('expectations_from_child', models.TextField()),
                ('socialization', models.BooleanField(default=False)),
                ('proforientation', models.BooleanField(default=False)),
                ('help_in_education', models.BooleanField(default=False)),
                ('able_to_visit_frequency', models.CharField(choices=[('ONCE_A_WEEK', '1 раз на тиждень'), ('ONCE_A_TWO_WEEKS', '1 раз на 2 тижні'), ('ONCE_A_MONTH', '1 раз на місяць'), ('OTHER', 'інше')], max_length=20)),
                ('ready_for_child_with_disabilities', models.BooleanField(default=False)),
                ('drink_alcohol', models.BooleanField(default=False)),
                ('drink_alcohol_frequency', models.CharField(blank=True, max_length=64, null=True)),
                ('smoke_cigarettes', models.BooleanField(default=False)),
                ('psychotropic_substances', models.BooleanField(default=False)),
                ('psychotropic_substances_names', models.CharField(blank=True, max_length=256, null=True)),
                ('drug_usage', models.BooleanField(default=False)),
                ('drug_usage_info', models.CharField(blank=True, max_length=128, null=True)),
                ('crime_convicted', models.BooleanField(default=False)),
                ('crime_convicted_description', models.CharField(blank=True, max_length=128, null=True)),
                ('parental_rights_deprived', models.BooleanField(default=False)),
                ('parental_rights_deprived_description', models.CharField(blank=True, max_length=128, null=True)),
                ('allow_to_use_personal_data', models.BooleanField(default=True)),
                ('program_found_out_place', models.CharField(choices=[('TV', 'Телебачення'), ('RADIO', 'Радіо'), ('OTHER_MEDIA', 'Інші ЗМІ'), ('FACEBOOK_OR_OTHER_SOCIAL_NETWORKS', 'Facebook або інші соціальні мережі'), ('INTERNET', 'Інтернет'), ('FRIENDS_RELATIVES_ACQUAINTANCES', 'Друзі, рідні, знайомі'), ('PAPERS', 'Друковані матеріали'), ('PRESENTATION_CONFERENCE', 'Презентація/конференція'), ('SOCIAL_SERVICE_CENTER', 'Центр соціальних служб для сім’ї, дітей та молоді (вкажіть район)'), ('CHILD_SERVICE', 'Служба у справах дітей (вкажіть район)')], max_length=64)),
                ('convenient_meeting_conditions', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MentorQuestionnaireChildrenWorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=256)),
                ('date_since', mentors.models.MonthYearField(max_length=7)),
                ('date_till', mentors.models.MonthYearField(max_length=7)),
                ('contact_info', models.CharField(max_length=512)),
                ('position', models.CharField(max_length=512)),
                ('duties', models.CharField(max_length=512)),
                ('children_age_group', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MentorQuestionnaireEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_type', models.CharField(choices=[('SCHOOL', 'Загальноосвітня школа'), ('UNIVERSITY', 'Університет, інститут, технікум'), ('EXTRA_EDUCATION', 'Додаткові курси, тренінги, семінари')], max_length=20)),
                ('institution', models.CharField(blank=True, default='', max_length=256)),
                ('year_of_admission', models.PositiveIntegerField()),
                ('year_of_graduation', models.PositiveIntegerField()),
                ('degree', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MentorQuestionnaireFamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('gender', models.CharField(choices=[('MALE', 'чоловіча'), ('FEMALE', 'жіноча')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('relation', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MentorQuestionnaireJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=False)),
                ('organization_name', models.CharField(max_length=512)),
                ('date_since', mentors.models.MonthYearField(max_length=7)),
                ('date_till', mentors.models.MonthYearField(max_length=7)),
                ('contact_info', models.CharField(max_length=512)),
                ('position', models.CharField(max_length=512)),
                ('duties', models.CharField(max_length=512)),
                ('reason_for_leaving', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='MentorSocialServiceCenterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infomeeting_date', models.DateField(blank=True, null=True)),
                ('passport_copy', models.BooleanField(default=False)),
                ('application', models.BooleanField(default=False)),
                ('certificate_of_good_conduct', models.BooleanField(default=False)),
                ('medical_certificate', models.BooleanField(default=False)),
                ('psychologist_meeting_date', models.DateField(blank=True, null=True)),
                ('psychologist_summary', models.TextField(blank=True, null=True)),
                ('recommended_to_training', models.BooleanField(default=False)),
                ('training_date', models.DateField(blank=True, null=True)),
                ('trainer_summary', models.TextField(blank=True, null=True)),
                ('admitted_to_child', models.BooleanField(default=False)),
                ('contract_number', models.CharField(blank=True, max_length=32, null=True)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='mentorees/post')),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proforientation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256)),
                ('profession_name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=512)),
                ('meeting_days', models.CharField(max_length=128)),
                ('business_description', models.TextField()),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(regex='\\+?1?\\d$')])),
            ],
        ),
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mentorees/story')),
                ('mentoree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_images', to='mentors.Mentoree')),
            ],
        ),
    ]
