# Generated by Django 2.1 on 2018-08-29 14:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_auto_20180829_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorLicenceKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('[a-zA-z]{2}\\d{3}[a-zA-z]{3}\\d{2}')])),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Mentor')),
            ],
        ),
    ]
