# Generated by Django 2.1 on 2018-08-30 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180830_1034'),
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('observation', models.TextField()),
                ('note_for_next_meeting', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MeetingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mentorees/meeting_images')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Mentoree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('date_of_birth', models.DateField()),
                ('dream', models.CharField(max_length=128)),
                ('want_to_become', models.CharField(max_length=32)),
                ('fears', models.CharField(max_length=128)),
                ('loves', models.CharField(max_length=64)),
                ('hates', models.CharField(max_length=64)),
                ('extra_data', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('profile_image', models.ImageField(upload_to='mentorees/profile_images')),
                ('hygiene', models.CharField(max_length=64)),
                ('will_help_to_became_independent', models.CharField(max_length=64)),
                ('emotional_state', models.CharField(max_length=64)),
                ('communication_skills', models.CharField(max_length=64)),
                ('how_orients_in_environment', models.CharField(max_length=64)),
                ('story', models.TextField()),
                ('organization', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mentorees/story_images')),
                ('mentoree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.Mentoree')),
            ],
        ),
    ]
