# Generated by Django 2.1 on 2018-08-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_meeting_meetingimage_mentoree_storyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorlicencekey',
            name='mentor',
        ),
    ]
