# Generated by Django 2.1.1 on 2018-11-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_auto_20181112_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorsocialservicecenterdata',
            name='admitted_to_child',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mentorsocialservicecenterdata',
            name='application',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mentorsocialservicecenterdata',
            name='certificate_of_good_conduct',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mentorsocialservicecenterdata',
            name='medical_certificate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mentorsocialservicecenterdata',
            name='passport_copy',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mentorsocialservicecenterdata',
            name='recommended_to_training',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
