# Generated by Django 2.1 on 2018-08-30 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_mentor_licence_key'),
        ('mentors', '0003_remove_mentorlicencekey_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('UKRAINE', 'Ukraine'), ('KYIV', 'Kyiv'), ('ZHYTOMYR', 'Zhytomyr')], max_length=16)),
                ('image', models.ImageField(upload_to='mentorees/post')),
                ('likes', models.PositiveSmallIntegerField(default=0)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Mentor')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Mentor')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mentors.Post')),
            ],
        ),
        migrations.AlterField(
            model_name='meetingimage',
            name='image',
            field=models.ImageField(upload_to='mentorees/meeting'),
        ),
        migrations.AlterField(
            model_name='mentoree',
            name='profile_image',
            field=models.ImageField(upload_to='mentorees/profile'),
        ),
        migrations.AlterField(
            model_name='storyimage',
            name='image',
            field=models.ImageField(upload_to='mentorees/story'),
        ),
    ]
