# Generated by Django 2.1.1 on 2018-11-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_auto_20181126_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='MIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsc_number', models.IntegerField()),
                ('address', models.CharField(max_length=2048)),
                ('schedule', models.CharField(max_length=2048)),
                ('phone_number_fax_str', models.CharField(max_length=2048)),
                ('email', models.EmailField(max_length=254)),
                ('region', models.CharField(max_length=2048)),
            ],
        ),
    ]
