# Generated by Django 2.1.1 on 2018-11-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0005_mia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mia',
            name='tsc_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
