# Generated by Django 2.1 on 2018-08-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0006_auto_20180830_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='region',
            field=models.CharField(choices=[('KYIV', 'Kyiv'), ('ZHYTOMYR', 'Zhytomyr')], max_length=16),
        ),
    ]
