# Generated by Django 2.1.1 on 2018-11-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0006_auto_20181127_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mia',
            name='tsc_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
