# Generated by Django 2.1.1 on 2018-11-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0007_auto_20181127_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('QUESTIONNAIRE', 'questionnaire'), ('MEDICAL_EXAM', 'medical_exam'), ('CONTRACT', 'contract')], max_length=10)),
                ('file', models.FileField(upload_to='mentorees/roadmap_docs')),
            ],
        ),
    ]
