# Generated by Django 2.1 on 2018-08-30 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20180830_1251'),
        ('mentors', '0008_auto_20180830_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='performer',
            field=models.ForeignKey(default='b541ff36-d8ed-4645-a2d8-0b34ce69c6c4', on_delete=django.db.models.deletion.CASCADE, to='users.Mentor'),
            preserve_default=False,
        ),
    ]
