# Generated by Django 2.1.1 on 2018-11-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0008_roadmapdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmapdoc',
            name='doc_type',
            field=models.CharField(choices=[('QUESTIONNAIRE', 'questionnaire'), ('MEDICAL_EXAM', 'medical_exam'), ('CONTRACT', 'contract')], max_length=15),
        ),
    ]
