# Generated by Django 2.1.1 on 2018-11-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0009_auto_20181128_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='mia',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mia',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
    ]
