# Generated by Django 2.1.1 on 2018-12-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0011_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='note_for_next_meeting',
            field=models.TextField(blank=True),
        ),
    ]
