# Generated by Django 2.1 on 2018-09-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0011_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
