# Generated by Django 2.1 on 2018-09-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0012_post_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoree',
            name='strengths',
            field=models.CharField(default='strengths', max_length=64),
            preserve_default=False,
        ),
    ]
