# Generated by Django 2.1 on 2018-09-04 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0013_mentoree_strengths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyimage',
            name='mentoree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_images', to='mentors.Mentoree'),
        ),
    ]
