# Generated by Django 2.1.1 on 2019-02-05 11:15

from django.db import migrations, models
import mentors.models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0013_auto_20181212_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorquestionnairechildrenworkexperience',
            name='children_age_group',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='mentorquestionnairechildrenworkexperience',
            name='contact_info',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='mentorquestionnairechildrenworkexperience',
            name='date_since',
            field=mentors.models.MonthYearField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='mentorquestionnairechildrenworkexperience',
            name='date_till',
            field=mentors.models.MonthYearField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='mentorquestionnairechildrenworkexperience',
            name='duties',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='mentorquestionnairechildrenworkexperience',
            name='organization_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mentorquestionnairechildrenworkexperience',
            name='position',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
