# Generated by Django 2.1 on 2018-09-04 09:27

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0014_auto_20180904_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentoree',
            name='communication_skills',
        ),
        migrations.RemoveField(
            model_name='mentoree',
            name='emotional_state',
        ),
        migrations.RemoveField(
            model_name='mentoree',
            name='how_orients_in_environment',
        ),
        migrations.RemoveField(
            model_name='mentoree',
            name='hygiene',
        ),
        migrations.RemoveField(
            model_name='mentoree',
            name='will_help_to_became_independent',
        ),
    ]
