# Generated by Django 2.1 on 2018-09-06 11:38

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0015_auto_20180904_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoree',
            name='extra_data_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(default=dict), size=None),
        ),
    ]
