# Generated by Django 2.1 on 2018-09-06 11:59

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0016_auto_20180906_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoree',
            name='extra_data_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(default=dict), blank=True, null=True, size=None),
        ),
    ]
