# Generated by Django 2.1.1 on 2018-09-11 09:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180904_1110'),
        ('mentors', '0017_auto_20180906_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='related_user',
        ),
        migrations.AlterField(
            model_name='mentorlicencekey',
            name='key',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='[a-zA-z]{2}\\d{3}[a-zA-z]{3}\\d{2}')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.Mentor'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', to='users.Mentor'),
        ),
    ]
