# Generated by Django 2.1.1 on 2018-09-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0018_auto_20180911_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(to='users.Mentor'),
        ),
    ]
