# Generated by Django 2.1.1 on 2018-09-11 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0019_auto_20180911_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='region',
        ),
    ]
