# Generated by Django 2.1.1 on 2018-09-12 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0020_remove_post_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentoree',
            name='address',
        ),
    ]
