# Generated by Django 2.1.1 on 2018-09-13 11:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mentors.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180904_1110'),
        ('mentors', '0021_remove_mentoree_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=512)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(regex='\\+?1?\\d$')])),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=265)),
                ('actual_address', models.CharField(max_length=521)),
                ('registration_address', models.CharField(max_length=521)),
                ('religion', models.CharField(choices=[('CHRISTIANITY', 'Christianity'), ('CATHOLICISM', 'Catholicism'), ('ORTHODOXY', 'Orthodoxy'), ('PROTESTANTISM', 'Protestantism'), ('JUDAISM', 'Judaism'), ('BUDDHISM', 'Buddhism'), ('OTHER', 'Other')], max_length=20)),
                ('local_church_visiting', models.CharField(blank=True, max_length=256, null=True)),
                ('local_church_visiting_frequency', models.CharField(blank=True, choices=[('CHRISTIANITY', 'Christianity'), ('CATHOLICISM', 'Catholicism'), ('ORTHODOXY', 'Orthodoxy'), ('PROTESTANTISM', 'Protestantism'), ('JUDAISM', 'Judaism'), ('BUDDHISM', 'Buddhism'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('health_self_estimation', models.CharField(max_length=265)),
                ('serious_diseases', models.CharField(max_length=265)),
                ('narcologist', models.BooleanField(default=False)),
                ('psychiatrist', models.BooleanField(default=False)),
                ('phthisiatrician', models.BooleanField(default=False)),
                ('therapist', models.BooleanField(default=False)),
                ('dermatovenereologist', models.BooleanField(default=False)),
                ('hospital_data', models.CharField(blank=True, max_length=512, null=True)),
                ('hiv_infected', models.BooleanField(default=False)),
                ('interests_and_hobbies', models.TextField()),
                ('marital_status', models.CharField(choices=[('MARRIED', 'married'), ('CIVIL_MARRIAGE', 'civil_marriage'), ('DIVORCED', 'divorced'), ('WIDOW', 'widow'), ('UNMARRIED', 'unmarried')], max_length=20)),
                ('home_type', models.CharField(choices=[('APARTMENT', 'apartment'), ('PRIVATE_HOUSE', 'private_house'), ('RENTED', 'rented')], max_length=20)),
                ('room_count', models.PositiveSmallIntegerField(default=1)),
                ('people_per_room', models.PositiveSmallIntegerField(default=1)),
                ('home_family_members_data', models.TextField()),
                ('pets_data', models.TextField()),
                ('join_reason', models.TextField()),
                ('helpful_specifics', models.TextField()),
                ('self_char', models.TextField()),
                ('want_to_help_reason', models.TextField()),
                ('expectations_from_child', models.TextField()),
                ('socialization', models.BooleanField(default=False)),
                ('proforientation', models.BooleanField(default=False)),
                ('help_in_education', models.BooleanField(default=False)),
                ('able_to_visit_frequency', models.CharField(choices=[('ONCE_A_WEEK', 'once_a_week'), ('TWICE_A_MONTH', 'twice_a_month'), ('ONCE_A_YEAR', 'once_a_year'), ('OTHER', 'other')], max_length=20)),
                ('ready_for_child_with_disabilities', models.BooleanField(default=False)),
                ('drink_alcohol', models.BooleanField(default=False)),
                ('drink_alcohol_frequency', models.CharField(blank=True, max_length=64, null=True)),
                ('smoke_cigarettes', models.BooleanField(default=False)),
                ('psychotropic_substances', models.BooleanField(default=False)),
                ('psychotropic_substances_names', models.CharField(blank=True, max_length=256, null=True)),
                ('drug_usage', models.BooleanField(default=False)),
                ('drug_usage_info', models.CharField(blank=True, max_length=128, null=True)),
                ('crime_convicted', models.BooleanField(default=False)),
                ('crime_convicted_description', models.CharField(blank=True, max_length=128, null=True)),
                ('parental_rights_deprived', models.BooleanField(default=False)),
                ('parental_rights_deprived_description', models.CharField(blank=True, max_length=128, null=True)),
                ('allow_to_use_personal_data', models.BooleanField(default=True)),
                ('program_found_out_place', models.CharField(choices=[('TV', 'tv'), ('RADIO', 'radio'), ('OTHER_MEDIA', 'other_media'), ('FACEBOOK_OR_OTHER_SOCIAL_NETWORKS', 'facebook_or_other_social_networks'), ('INTERNET', 'internet'), ('FRIENDS_RELATIVES_ACQUAINTANCES', 'friends_relatives_acquaintances'), ('PAPERS', 'papers'), ('PRESENTATION_CONFERENCE', 'presentation_conference'), ('SOCIAL_SERVICE_CENTER', 'social_service_center'), ('CHILD_SERVICE', 'child_service')], max_length=32)),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Mentor')),
            ],
        ),
        migrations.CreateModel(
            name='MentorQuestionnaireChildrenWorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=256)),
                ('date_since', mentors.models.MonthYearField(max_length=7)),
                ('date_till', mentors.models.MonthYearField(max_length=7)),
                ('contact_info', models.CharField(max_length=512)),
                ('position', models.CharField(max_length=512)),
                ('duties', models.CharField(max_length=512)),
                ('children_age_group', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MentorQuestionnaireEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_admission', models.PositiveIntegerField()),
                ('year_of_graduation', models.PositiveIntegerField()),
                ('degree', models.CharField(max_length=256)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.MentorQuestionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='MentorQuestionnaireFamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('gender', models.PositiveSmallIntegerField(choices=[('MALE', 0), ('FEMALE', 1)])),
                ('date_of_birth', models.DateField()),
                ('relation', models.CharField(max_length=64)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.MentorQuestionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='MentorQuestionnaireJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=False)),
                ('organization_name', models.CharField(max_length=512)),
                ('date_since', mentors.models.MonthYearField(max_length=7)),
                ('date_till', mentors.models.MonthYearField(max_length=7)),
                ('position', models.CharField(max_length=512)),
                ('duties', models.CharField(max_length=512)),
                ('reason_for_leaving', models.CharField(max_length=512)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.MentorQuestionnaire')),
            ],
        ),
    ]
