# Generated by Django 2.1.1 on 2018-09-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0022_mentorquestionnaire_mentorquestionnairechildrenworkexperience_mentorquestionnaireeducation_mentorque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorquestionnairefamilymember',
            name='gender',
            field=models.CharField(choices=[('MALE', 0), ('FEMALE', 1)], max_length=10),
        ),
    ]
