# Generated by Django 2.1.1 on 2018-09-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0023_auto_20180913_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorquestionnaire',
            name='able_to_visit_frequency',
            field=models.CharField(choices=[('ONCE_A_WEEK', '1 раз на тиждень'), ('ONCE_A_TWO_WEEKS', '1 раз на 2 тижні'), ('ONCE_A_MONTH', '1 раз на місяць'), ('OTHER', 'інше')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mentorquestionnaire',
            name='home_type',
            field=models.CharField(choices=[('APARTMENT', 'квартира'), ('PRIVATE_HOUSE', 'приватний будинок'), ('RENTED', 'орендоване житло')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mentorquestionnaire',
            name='local_church_visiting_frequency',
            field=models.CharField(blank=True, choices=[('CHRISTIANITY', 'Християнство'), ('CATHOLICISM', 'Католицизм'), ('ORTHODOXY', 'Православ’я'), ('PROTESTANTISM', 'Протестантизм'), ('JUDAISM', 'Іудаїзм'), ('BUDDHISM', 'Буддизм'), ('ISLAM', 'Іслам'), ('OTHER', 'Інше')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mentorquestionnaire',
            name='marital_status',
            field=models.CharField(choices=[('MARRIED', 'Одружений/одружена'), ('CIVIL_MARRIAGE', 'Цивільний шлюб'), ('DIVORCED', 'Розлучений/розлучена'), ('WIDOW', 'Удовець/удова'), ('UNMARRIED', 'Неодружений/неодружена')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mentorquestionnaire',
            name='program_found_out_place',
            field=models.CharField(choices=[('TV', 'Телебачення'), ('RADIO', 'Радіо'), ('OTHER_MEDIA', 'Інші ЗМІ'), ('FACEBOOK_OR_OTHER_SOCIAL_NETWORKS', 'Facebook або інші соціальні мережі'), ('INTERNET', 'Інтернет'), ('FRIENDS_RELATIVES_ACQUAINTANCES', 'Друзі, рідні, знайомі'), ('PAPERS', 'Друковані матеріали'), ('PRESENTATION_CONFERENCE', 'Презентація/конференція'), ('SOCIAL_SERVICE_CENTER', 'Центр соціальних служб для сім’ї, дітей та молоді (вкажіть район)'), ('CHILD_SERVICE', 'Служба у справах дітей (вкажіть район)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='mentorquestionnaire',
            name='religion',
            field=models.CharField(choices=[('CHRISTIANITY', 'Християнство'), ('CATHOLICISM', 'Католицизм'), ('ORTHODOXY', 'Православ’я'), ('PROTESTANTISM', 'Протестантизм'), ('JUDAISM', 'Іудаїзм'), ('BUDDHISM', 'Буддизм'), ('ISLAM', 'Іслам'), ('OTHER', 'Інше')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mentorquestionnairefamilymember',
            name='gender',
            field=models.CharField(choices=[('MALE', 'чоловіча'), ('FEMALE', 'жіноча')], max_length=10),
        ),
    ]
