# Generated by Django 2.1.1 on 2018-09-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0024_auto_20180913_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorquestionnaire',
            name='serious_diseases',
        ),
    ]
