# Generated by Django 2.1.1 on 2018-09-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0025_remove_mentorquestionnaire_serious_diseases'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorquestionnaire',
            name='serious_diseases',
            field=models.BooleanField(default=False),
        ),
    ]
