# Generated by Django 2.1.1 on 2018-09-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0026_mentorquestionnaire_serious_diseases'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorquestionnaireeducation',
            name='education_type',
            field=models.CharField(choices=[('SCHOOL', 'Загальноосвітня школа'), ('UNIVERSITY', 'Університет, інститут, технікум'), ('EXTRA_EDUCATION', 'Додаткові курси, тренінги, семінари')], default='SCHOOL', max_length=20),
            preserve_default=False,
        ),
    ]
