# Generated by Django 2.1.1 on 2018-09-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0027_mentorquestionnaireeducation_education_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorquestionnairejob',
            name='contact_info',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
