# Generated by Django 2.1.1 on 2018-09-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0028_mentorquestionnairejob_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorquestionnaire',
            name='local_church_visiting_frequency',
            field=models.CharField(blank=True, choices=[('ONCE_A_WEEK', 'раз на тиждень'), ('ONCE_A_MONTH', 'раз на місяць'), ('ONCE_A_YEAR', 'один раз на рік'), ('OTHER', 'інше')], max_length=20, null=True),
        ),
    ]
