# Generated by Django 2.1.1 on 2018-09-17 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0029_auto_20180914_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorquestionnairechildrenworkexperience',
            name='questionnaire',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, to='mentors.MentorQuestionnaire'),
            preserve_default=False,
        ),
    ]
