# Generated by Django 2.1.1 on 2018-09-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0030_mentorquestionnairechildrenworkexperience_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorquestionnaire',
            name='convenient_meeting_conditions',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentorquestionnaire',
            name='program_found_out_place',
            field=models.CharField(choices=[('TV', 'Телебачення'), ('RADIO', 'Радіо'), ('OTHER_MEDIA', 'Інші ЗМІ'), ('FACEBOOK_OR_OTHER_SOCIAL_NETWORKS', 'Facebook або інші соціальні мережі'), ('INTERNET', 'Інтернет'), ('FRIENDS_RELATIVES_ACQUAINTANCES', 'Друзі, рідні, знайомі'), ('PAPERS', 'Друковані матеріали'), ('PRESENTATION_CONFERENCE', 'Презентація/конференція'), ('SOCIAL_SERVICE_CENTER', 'Центр соціальних служб для сім’ї, дітей та молоді (вкажіть район)'), ('CHILD_SERVICE', 'Служба у справах дітей (вкажіть район)')], max_length=64),
        ),
    ]
