# Generated by Django 2.1.1 on 2018-09-18 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0031_auto_20180917_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoree',
            name='extra_data',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mentoree',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Organization'),
        ),
        migrations.AlterField(
            model_name='mentoree',
            name='strengths',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
