# Generated by Django 2.1.1 on 2018-09-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0032_auto_20180918_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoree',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentoree',
            name='dream',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mentoree',
            name='fears',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mentoree',
            name='hates',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='mentoree',
            name='last_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='mentoree',
            name='loves',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='mentoree',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='mentorees/profile'),
        ),
        migrations.AlterField(
            model_name='mentoree',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentoree',
            name='want_to_become',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
