# Generated by Django 2.1.1 on 2018-09-25 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0034_auto_20180920_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorquestionnaire',
            name='mentor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='users.Mentor'),
        ),
    ]
