# Generated by Django 2.1.1 on 2018-09-27 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0035_auto_20180925_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforientation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256)),
                ('profession_name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=512)),
                ('meeting_days', models.CharField(max_length=128)),
                ('business_description', models.TextField()),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(regex='\\+?1?\\d$')])),
            ],
        ),
    ]
