# Generated by Django 2.1.1 on 2018-09-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_socialservicecenterassessment_mentor'),
        ('mentors', '0036_proforientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforientation',
            name='related_mentor',
            field=models.ManyToManyField(to='users.Mentor'),
        ),
    ]
