# Generated by Django 2.1.1 on 2018-10-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0038_auto_20181001_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorquestionnaire',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
