# Generated by Django 2.1.1 on 2018-10-08 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0040_mentorsocialservicecenterdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorsocialservicecenterdata',
            name='mentor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_service_center_data', to='users.Mentor'),
        ),
    ]
