# Generated by Django 2.1.1 on 2018-10-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0041_auto_20181008_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorquestionnaireeducation',
            name='institution',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
