# Generated by Django 2.1.1 on 2018-10-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialServiceVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.URLField()),
                ('page', models.IntegerField(choices=[(1, 'Main'), (2, 'Video Mentor')])),
            ],
        ),
    ]
