# Generated by Django 2.1.1 on 2018-11-19 12:01

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSocialServiceCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('region', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=512)),
                ('phone_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(regex='\\+?1?\\d$')]), size=None)),
            ],
        ),
    ]
