# Generated by Django 2.1.1 on 2018-11-19 12:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_services', '0003_auto_20181119_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesocialservicecenter',
            name='phone_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), size=None),
        ),
    ]
