# Generated by Django 2.1.1 on 2018-11-27 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181125_2315'),
        ('social_services', '0006_remove_basesocialservicecenter_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesocialservicecenter',
            name='service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.SocialServiceCenter'),
        ),
    ]
