# Generated by Django 2.1.1 on 2018-11-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_services', '0007_basesocialservicecenter_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesocialservicecenter',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='basesocialservicecenter',
            name='region',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
