# Generated by Django 2.1.1 on 2018-11-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181112_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='questionnaire_creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
