# Generated by Django 2.1.1 on 2018-11-16 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181112_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicservice',
            name='licence',
            field=models.CharField(default='AAQN 83', max_length=7, validators=[django.core.validators.RegexValidator(regex='[A-Z]{4}\\s{1}\\d{2}')]),
        ),
    ]
