# Generated by Django 2.1 on 2018-08-28 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180827_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='first_name',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='middle_name',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='phone_number',
            field=models.CharField(default=1, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'govern_user'), (1, 'mentor'), (2, 'social_service_center'), (3, 'public_service'), (4, 'institution'), (5, 'child_service'), (6, 'project_assistant')], default=1),
            preserve_default=False,
        ),
    ]
