# Generated by Django 2.1 on 2018-08-28 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180828_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(regex='\\+?1?\\d$')]),
        ),
    ]
