# Generated by Django 2.1 on 2018-08-28 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180828_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectassistant',
            name='another_assistance_ways_names',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectassistant',
            name='city',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectassistant',
            name='financial_support',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectassistant',
            name='first_name',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectassistant',
            name='last_name',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectassistant',
            name='master_classes_names',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectassistant',
            name='mentoring_popularization',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectassistant',
            name='phone_number',
            field=models.CharField(default=1, max_length=17, validators=[django.core.validators.RegexValidator(regex='\\+?1?\\d$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectassistant',
            name='profession_company_address',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectassistant',
            name='profession_company_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectassistant',
            name='profession_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
