# Generated by Django 2.1 on 2018-08-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180828_1240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectAssistant',
            new_name='Volunteer',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'govern_user'), (1, 'mentor'), (2, 'social_service_center'), (3, 'public_service'), (4, 'institution'), (5, 'child_service'), (6, 'volunteer')]),
        ),
    ]
