# Generated by Django 2.1.1 on 2018-11-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181118_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mentorees/coordinator_images'),
        ),
    ]
