# Generated by Django 2.1 on 2018-08-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180828_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='middle_name',
            new_name='last_name',
        ),
    ]
