# Generated by Django 2.1.1 on 2018-11-27 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_services', '0007_basesocialservicecenter_service'),
        ('users', '0008_auto_20181125_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='base_social_service_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_services.BaseSocialServiceCenter'),
        ),
    ]
