# Generated by Django 2.1.1 on 2018-11-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_mentor_base_social_service_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicservice',
            name='status',
            field=models.CharField(choices=[('NOT_SPECIFIED', 'Не визначений'), ('KNOW_ABOUT_EXISTING', 'Знаємо про її існування'), ('COOPERATION_AGREEMENT', 'Домовленість про співпрацю'), ('CONTRACT_SIGNED', 'Підписаний договір')], default='NOT_SPECIFIED', max_length=64),
        ),
    ]
