# Generated by Django 2.1.1 on 2018-12-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20181130_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='make_master_classes',
            field=models.BooleanField(default=True),
        ),
    ]
