# Generated by Django 2.1 on 2018-08-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180830_0744'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Institution',
            new_name='Organization',
        ),
    ]
