# Generated by Django 2.1.1 on 2018-12-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_volunteer_make_master_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='talk_about_profession',
            field=models.BooleanField(default=True),
        ),
    ]
