# Generated by Django 2.1 on 2018-08-30 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_remove_mentorlicencekey_mentor'),
        ('users', '0012_mentor_mentoree'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='licence_key',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentors.MentorLicenceKey'),
        ),
    ]
