# Generated by Django 2.1 on 2018-08-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_mentor_licence_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'govern_user'), (1, 'mentor'), (2, 'social_service_center'), (3, 'public_service'), (4, 'organization'), (5, 'child_service'), (6, 'volunteer')]),
        ),
    ]
