# Generated by Django 2.1.1 on 2018-12-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20181204_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='another_assistance_ways_names',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='master_classes_names',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='profession_company_address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='profession_company_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='profession_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
