# Generated by Django 2.1.1 on 2018-12-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20181204_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicservice',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='public_services/profile_images'),
        ),
    ]
