# Generated by Django 2.1 on 2018-09-04 08:10

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_mentor_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(default='temp', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(default='organization_name', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='phone_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(regex='\\+?1?\\d$')]), default=['+380988888888'], size=None),
            preserve_default=False,
        ),
    ]
