# Generated by Django 2.1.1 on 2018-12-07 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20181205_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('logo', models.ImageField(upload_to='useful_contacts')),
                ('description', models.TextField()),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(regex='\\+?1?\\d$')])),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=4096)),
            ],
        ),
    ]
