# Generated by Django 2.1.1 on 2018-09-24 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180904_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialservicecenter',
            name='mentor_license_key',
        ),
        migrations.AddField(
            model_name='mentor',
            name='social_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.SocialServiceCenter'),
        ),
    ]
