# Generated by Django 2.1.1 on 2018-09-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20180924_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialservicecenter',
            name='name',
            field=models.CharField(default='SocCenter', max_length=256),
            preserve_default=False,
        ),
    ]
