# Generated by Django 2.1.1 on 2018-12-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20181212_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('ORGANIZATION', 'organization'), ('SSD', 'ssd')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
