# Generated by Django 2.1.1 on 2018-09-24 12:57

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20180924_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='email',
            field=models.EmailField(default='mail@mail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinator',
            name='full_name',
            field=models.CharField(default='full name', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinator',
            name='phone_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(regex='\\+?1?\\d$')]), default=['+380888888888'], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialservicecenter',
            name='address',
            field=models.CharField(default='address', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialservicecenter',
            name='city',
            field=models.CharField(default='city', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialservicecenter',
            name='phone_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(regex='\\+?1?\\d$')]), default=['+380888888888'], size=None),
            preserve_default=False,
        ),
    ]
