# Generated by Django 2.1.1 on 2018-12-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_material_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcategory',
            name='material_type',
            field=models.CharField(choices=[('ORGANIZATION', 'organization'), ('SSD', 'ssd')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
