# Generated by Django 2.1.1 on 2018-09-24 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20180924_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='mentor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Mentor'),
        ),
    ]
