# Generated by Django 2.1.1 on 2018-12-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_improvement'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialservicecenter',
            name='profile_image',
            field=models.ImageField(default='1.jpg', upload_to='social_services/profile_images'),
            preserve_default=False,
        ),
    ]
