# Generated by Django 2.1.1 on 2018-09-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20180924_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='image',
            field=models.ImageField(default='test', upload_to='mentorees/coordinator_images'),
            preserve_default=False,
        ),
    ]
