# Generated by Django 2.1.1 on 2018-09-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_coordinator_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
