# Generated by Django 2.1.1 on 2018-09-25 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_mentor_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='date_of_birth',
        ),
    ]
