# Generated by Django 2.1.1 on 2018-09-25 22:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_mentor_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialServiceCenterAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('mentor_help_description', models.TextField()),
                ('mentor_pair_help_description', models.TextField()),
                ('ssc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SocialServiceCenter')),
            ],
        ),
        migrations.CreateModel(
            name='SocialServiceCenterReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('ssc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SocialServiceCenter')),
            ],
        ),
    ]
