# Generated by Django 2.1.1 on 2019-02-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20190211_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('ORGANIZATION', 'organization'), ('SSD', 'ssd')], max_length=48),
        ),
    ]
