# Generated by Django 2.1.1 on 2018-09-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_socialservicecenterassessment_socialservicecenterreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialservicecenterassessment',
            name='mentor_help_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialservicecenterassessment',
            name='mentor_pair_help_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
