# Generated by Django 2.1.1 on 2018-09-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20180926_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialservicecenterassessment',
            name='mentor',
            field=models.OneToOneField(default='fff31735-e963-40fd-9230-ea8400313a98', on_delete=django.db.models.deletion.CASCADE, to='users.Mentor'),
            preserve_default=False,
        ),
    ]
