# Generated by Django 2.1.1 on 2018-10-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_socialservicecenterassessment_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='licenced',
            field=models.BooleanField(default=False),
        ),
    ]
