# Generated by Django 2.1.1 on 2018-10-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_mentor_licenced'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='status',
            field=models.CharField(default='PASSED_INFO_MEETING', max_length=32),
            preserve_default=False,
        ),
    ]
