# Generated by Django 2.1.1 on 2018-10-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_mentor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='status',
            field=models.CharField(choices=[('PASSED_INFO_MEETING', 'Пройшов інфо-зустріч'), ('PASSED_TRAINING', 'Пройшов тренінг'), ('REJECTED_TO_BE_MENTOR', 'Відмовився бути наставником'), ('PASSED_INTERVIEW_WITH_PSYCHOLOGIST', 'Пройшов співбесіду з психологом'), ('SELECTED_FOR_MENTOREE', 'Підібраний для вихованця'), ('ACTIVE_INTERACTION', 'Активна взаємодія'), ('PAIR_DISBANDED', 'Пара розформована')], max_length=32),
        ),
    ]
