# Generated by Django 2.1.1 on 2018-10-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20181005_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='application',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor',
            name='certificate_of_good_conduct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor',
            name='medical_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor',
            name='passport_copy',
            field=models.BooleanField(default=False),
        ),
    ]
