# Generated by Django 2.1.1 on 2018-10-05 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20181005_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicservice',
            name='social_service_center',
            field=models.ForeignKey(default='d796c9c1-ac20-4a2c-aa9f-2af278b6734e', on_delete=django.db.models.deletion.CASCADE, to='users.SocialServiceCenter'),
            preserve_default=False,
        ),
    ]
