# Generated by Django 2.1.1 on 2018-10-05 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20181005_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='public_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.PublicService'),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='social_service_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SocialServiceCenter'),
        ),
    ]
