# Generated by Django 2.1.1 on 2018-10-05 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20181005_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicservice',
            name='address',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicservice',
            name='email',
            field=models.EmailField(default='test@mail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicservice',
            name='max_pair_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='publicservice',
            name='phone_number',
            field=models.CharField(default='380988775567', max_length=17, validators=[django.core.validators.RegexValidator(regex='\\+?1?\\d$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicservice',
            name='website',
            field=models.URLField(default='site.com'),
            preserve_default=False,
        ),
    ]
