# Generated by Django 2.1.1 on 2018-10-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20181005_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicservice',
            name='name',
            field=models.CharField(default='soc service center', max_length=128),
            preserve_default=False,
        ),
    ]
