# Generated by Django 2.1.1 on 2018-10-08 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_publicservice_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='social_service_center',
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='mentor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Mentor'),
        ),
    ]
