# Generated by Django 2.1.1 on 2018-10-08 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20181008_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='application',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='certificate_of_good_conduct',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='medical_certificate',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='passport_copy',
        ),
    ]
