# Generated by Django 2.1.1 on 2018-10-10 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20181008_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='public_service',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='social_service_center',
        ),
        migrations.AddField(
            model_name='publicservice',
            name='coordinator',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.Coordinator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialservicecenter',
            name='coordinator',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to='users.Coordinator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='mentor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Mentor'),
        ),
    ]
