# Generated by Django 2.1.1 on 2018-10-11 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20181010_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicservice',
            name='coordinator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_service', to='users.Coordinator'),
        ),
        migrations.AlterField(
            model_name='socialservicecenter',
            name='coordinator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_service_center', to='users.Coordinator'),
        ),
    ]
