# Generated by Django 2.1.1 on 2018-10-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20181012_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the user account currently active', verbose_name='active'),
        ),
    ]
