# Generated by Django 2.1.1 on 2018-10-15 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20181012_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='mentor',
        ),
        migrations.AddField(
            model_name='mentor',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Coordinator'),
        ),
    ]
