# Generated by Django 2.1.1 on 2018-10-17 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_services', '0003_auto_20181012_1648'),
        ('users', '0043_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='master_key',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_services.SocialServiceMasterKey'),
        ),
    ]
