# Generated by Django 2.1.1 on 2018-10-15 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20181015_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor', to='users.Coordinator'),
        ),
    ]
