# Generated by Django 2.1.1 on 2018-10-16 12:16
import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20181015_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='actual_address',
            field=models.CharField(default='address', max_length=521),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='date_of_birth',
            field=models.DateField(default='2011-11-11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='questionnaire_creation_date',
            field=models.DateField(default='2011-11-11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='master_key',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='social_services.SocialServiceMasterKey'),
        ),
        migrations.AlterField(
            model_name='user',
            name='master_key',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       to='social_services.SocialServiceMasterKey'),
        ),
    ]
