# Generated by Django 2.1.1 on 2018-10-17 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_user_master_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='master_key',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_services.SocialServiceMasterKey'),
        ),
    ]
