# Generated by Django 2.1.1 on 2018-10-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20181017_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='master_key',
        ),
        migrations.AddField(
            model_name='user',
            name='user_master_key',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
