# Generated by Django 2.1.1 on 2018-10-17 12:57

from django.db import migrations, models
import django.db.models.deletion
import users.constants


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicservice',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='socialservicecenter',
            name='coordinator',
        ),
        migrations.AddField(
            model_name='coordinator',
            name='public_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.PublicService'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='social_service_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SocialServiceCenter'),
        ),
        migrations.AddField(
            model_name='publicservice',
            name='status',
            field=models.CharField(choices=[('NOT_SPECIFIED', 'Не визначений'), ('KNOW_ABOUT_EXISTING', 'Знаємо про її існування'), ('COOPERATION_AGREEMENT', 'Домовленість про співпрацю'), ('CONTRACT_SIGNED', 'Підписаний договір')], default=users.constants.PublicServiceStatuses('Не визначений'), max_length=64),
        ),
    ]
