# Generated by Django 2.1.1 on 2018-10-19 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20181017_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicservice',
            name='contract_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='public_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='users.PublicService'),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='social_service_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='users.SocialServiceCenter'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentors', to='users.Coordinator'),
        ),
    ]
