# Generated by Django 2.1.1 on 2018-10-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_auto_20181019_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicservice',
            name='profile_image',
            field=models.ImageField(default='img.png', upload_to='public_services/profile_images'),
            preserve_default=False,
        ),
    ]
