# Generated by Django 2.1.1 on 2018-11-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_user_is_active'),
        ('users', '0049_publicservice_profile_image'),
    ]

    operations = [
    ]
