# Generated by Django 2.1.1 on 2018-11-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_merge_20181102_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'govern_user'), (1, 'mentor'), (2, 'social_service_center'), (3, 'public_service'), (4, 'organization'), (5, 'child_service'), (6, 'volunteer'), (7, 'social_policy_ministry')]),
        ),
    ]
