# Generated by Django 2.1.1 on 2018-11-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentorSchoolVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('video', models.FileField(blank=True, null=True, upload_to='govern_users/mentor_school_videos')),
                ('thumbnail', models.ImageField(upload_to='govern_users/mentor_school_videos/thumbnails')),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MentorSchoolVideoExtraMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='govern_users/mentor_school_videos/extra_materials')),
            ],
        ),
        migrations.CreateModel(
            name='MentorTip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='govern_users/mentor_tips')),
            ],
        ),
        migrations.CreateModel(
            name='TipOfTheDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('last_swap_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
