# Generated by Django 2.1 on 2018-08-31 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('govern_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorSchoolVideoExtraMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='govern_users/mentor_school_videos/extra_materials')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='govern_users.MentorSchoolVideo')),
            ],
        ),
    ]
