# Generated by Django 2.1.1 on 2018-11-12 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('govern_users', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoftheday',
            name='watched_by',
            field=models.ManyToManyField(to='users.Mentor'),
        ),
        migrations.AddField(
            model_name='mentorschoolvideoextramaterial',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_materials', to='govern_users.MentorSchoolVideo'),
        ),
        migrations.AddField(
            model_name='mentorschoolvideo',
            name='watched_by',
            field=models.ManyToManyField(blank=True, to='users.Mentor'),
        ),
    ]
