# Generated by Django 2.1 on 2018-08-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govern_users', '0002_mentorschoolvideoextramaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentortip',
            name='image',
            field=models.ImageField(default='image', upload_to='', verbose_name='govern_users/mentor_tips'),
            preserve_default=False,
        ),
    ]
