# Generated by Django 2.1 on 2018-09-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govern_users', '0003_mentortip_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorschoolvideo',
            name='watched_by',
            field=models.ManyToManyField(blank=True, to='users.Mentor'),
        ),
    ]
