# Generated by Django 2.1 on 2018-09-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govern_users', '0004_auto_20180904_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorschoolvideo',
            name='thumbnail',
            field=models.ImageField(default='default', upload_to='govern_users/mentor_school_videos/thumbnails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorschoolvideo',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorschoolvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='govern_users/mentor_school_videos'),
        ),
    ]
