# Generated by Django 2.1 on 2018-09-05 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('govern_users', '0005_auto_20180905_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorschoolvideoextramaterial',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_materials', to='govern_users.MentorSchoolVideo'),
        ),
    ]
