# Generated by Django 2.1.1 on 2018-09-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govern_users', '0006_auto_20180905_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorschoolvideoextramaterial',
            name='file',
            field=models.FileField(upload_to='govern_users/mentor_school_videos/extra_materials'),
        ),
        migrations.AlterField(
            model_name='mentortip',
            name='image',
            field=models.ImageField(upload_to='govern_users/mentor_tips'),
        ),
    ]
