# Generated by Django 2.1.1 on 2018-10-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govern_users', '0007_auto_20180911_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipOfTheDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=256)),
                ('last_swap_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
