# Generated by Django 2.1.1 on 2018-10-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govern_users', '0008_tipoftheday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoftheday',
            old_name='context',
            new_name='content',
        ),
    ]
