# Generated by Django 2.1.1 on 2018-10-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_mentor_licenced'),
        ('govern_users', '0009_auto_20181002_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoftheday',
            name='watched_by',
            field=models.ManyToManyField(to='users.Mentor'),
        ),
    ]
