# Generated by Django 2.1.1 on 2018-10-17 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicOrganizationMasterKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_key', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^.{8,12}$')])),
            ],
        ),
        migrations.CreateModel(
            name='PublicOrganizationVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.URLField()),
                ('page', models.IntegerField(choices=[(1, 'Main'), (2, 'Video Mentor')])),
            ],
        ),
    ]
