# Generated by Django 2.1.1 on 2018-10-03 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialServiceMasterKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_key', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^.{8,12}$')])),
            ],
        ),
    ]
