# Generated by Django 2.1.1 on 2019-01-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_policy', '0002_auto_20190108_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraregiondata',
            old_name='region_name',
            new_name='region',
        ),
    ]
