# Generated by Django 2.1.1 on 2019-01-09 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_policy', '0003_auto_20190108_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('video_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SPMaterialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons')),
            ],
            options={
                'verbose_name': 'Material category',
                'verbose_name_plural': 'Material categories',
            },
        ),
        migrations.AddField(
            model_name='spmaterial',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_policy.SPMaterialCategory'),
        ),
    ]
